### ISSUE TITLE
Subpixel rendering

### ISSUE THREAD

**Issue by solendil** [solendil/FractalJS#11]

**Comment by solendil** [comment]
The difference subpixel rendering makes can be impressive.

No antialiasing : 
![fractal](https://cloud.githubusercontent.com/assets/1157957/9658959/7ff3ffec-524d-11e5-9647-21c23e7171db.png)

Quincunx 5x antialiasing:
![fractal 1](https://cloud.githubusercontent.com/assets/1157957/9658968/8d7ed4d4-524d-11e5-86b4-1d10da8eb465.png)

50x antialising:
![fractal 2](https://cloud.githubusercontent.com/assets/1157957/9658977/9d1a0d64-524d-11e5-9a43-1086d858913f.png)

This feature will need some love (automatic enhancement based upon variance of samples in each individual pixel? quality slider or button?) This will wait for the implementation of the smooth iteration count which will also have a drastic effect on image quality.

**Comment by methusalah** [comment]
very nice !
