### ISSUE TITLE
Possible to have FJS directly onto welcome page of the github?

### ISSUE THREAD

**Issue by methusalah** [solendil/FractalJS#19]
It would demonstrate immediatly the strong embedability.

**Comment by solendil** [comment]
Unfortunately, I've already looked into this, and I'm not the first one http://stackoverflow.com/questions/4279611/how-to-embed-a-video-into-github-readme-md

It seems to be impossible at the moment; but maybe I will use the trick described above to display a fake image of a user interface to trick people into clicking on it...
