### ISSUE TITLE
Continuous Zoom

### ISSUE THREAD

**Issue by offsky** [solendil/FractalJS#35]
It would be awesome to have a continuous smooth zoom as you hold the mouse button down.

XaoS does this: http://matek.hu/xaos/doku.php

I saved this example from many years ago and no longer can find the source, but here it is:
[jsFractalZoomer1.html.zip](https://github.com/solendil/FractalJS/files/109064/jsFractalZoomer1.html.zip)

**Comment by solendil** [comment]
Hi offsky. 

Thank you **very much** for the code you provided. I didn't know such a javascript port of Xaos existed in JS. I'm impressed. This code might prove a very useful source of cool algorithms for FractalJS in the future. 

As for Xaos continuous zoom, it's certainly impressive, but I see two problems:

1) I'm not very fond of Xaos UX. Mouse control is sleek, but it lacks speed and/or precision, even in its desktop version. The "Google Map" UX of FractalJS is cruder, but IMO it's faster and more precise.
2) Though Franz Korntner's code is quite optimized, and zooming fullscreen remains fluid, the picture is quickly blurry and full of artifacts. It's not sure that significant optimizations are possible. FractalJS seems faster.

So thanks again for the code you provided, but I will focus on other features for the time being.
