### ISSUE TITLE
Automate palette density or find a better coloring algorithm

### ISSUE THREAD

**Issue by solendil** [solendil/FractalJS#44]
The goal being that the user is always presented with a beautiful picture

**Comment by solendil** [comment]
I tried Pauldebrot's multiwave coloring : http://www.fractalforums.com/images-showcase-%28rate-my-fractal%29/mandelbrot-safari/
But although it gives spectacular results when adjusted for a given zoom or picture, a single palette cannot fit the entire set (for example a zoom in elephant valley and one in scepters valley require different parameters and logarithm strength).
I shall test histograms methods.

**Comment by methusalah** [comment]
Pauldebrot's multiwave coloring is awsome ! Will you include it in FractalJX, cohabiting with other colorings?

**Comment by solendil** [comment]
Pauldebrot's algorithm has 47 different config variables (!) while one of the goals of FractalJS is to remain dead simple (3 coloring variables for the moment: palette, offset, density). I will include Pauldebrot's algorithm (or a variation thereof) only if I manage to reduce its configuration to a handful of simple variables. Thus the problem is more a UX problem than a coding one (as often)...

**Comment by solendil** [comment]
TODO in V3. I tried two approaches so far:
* using the sqrt of iterations count is better (but will invalidate current bookmarks, unless opt-in through a variable)
* adjust palette on redraw (not comfortable to use...)

Will try to have something soon...

**Comment by solendil** [comment]
Done at last.

I spent a few days toying with Pauldebrot Multiwave. Results of these experiments are in branch pauldebrot-tests. The algorithm is quick enough to run realtime, but it is definitely very tricky to find nice palettes with it. Especially palettes that give good results in FractalJS. It is more amenable to very deep zooms.

So using a simple transfer function sqrt(iter) is the simplest solution that gives good result in 90% of cases. For extreme cases, the slider is always there.

The change is hidden: current bookmarks work with the old transfer function (linear), and the new transfer function (sqrt) is automatically activated upon choosing a new palette. There's no way to go back to the old transfer function when selected.
