### ISSUE TITLE
Embed HTML code does not show up

### ISSUE THREAD

**Issue by TrakJohnson** [solendil/FractalJS#52]
The Embed HTML code does not seem to show up for any fractal.

![image](https://cloud.githubusercontent.com/assets/9513815/19490948/7b5e411e-9571-11e6-8e99-b0536b371637.png)

I can get it through the Inspect tool though:

![image](https://cloud.githubusercontent.com/assets/9513815/19491194/54e679ba-9572-11e6-9ca3-7cdeccd645a2.png)

I tried it on Chrome 53 & Edge 38

**Comment by solendil** [comment]
Thank you very much for your reporting. 
Since the last version of FractalJS, the ability to embed fractals in webpages is no longer available.
