### ISSUE TITLE
Performance improvements & modern technologies

### ISSUE THREAD

**Issue by solendil** [solendil/FractalJS#9]
FractalJS must be a showcase for Javascript technologies. As such, it needs to implement the following technologies:
- [x] ~~[Webworkers](https://en.wikipedia.org/wiki/Web_worker)~~
- [x] [asm.js](https://en.wikipedia.org/wiki/Asm.js)
- [ ] [WebGL](https://en.wikipedia.org/wiki/WebGL)
- [ ] [ES6 or Harmony or Ecma262 or whatever the name](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf)
- [ ] [WebAssembly](https://github.com/WebAssembly) ?

**Comment by solendil** [comment]
Webworkers implementation is well under way. It works, but you know the 80/20 rule, so there is still a lot of work. Preliminary results with Chrome : the performance improvement is around 3.1x with 4 workers (eg from 4759ms to 1544ms). For the moment, I pass the buffers by copy instead of by reference; some improvements could be attained here. What remains to be done:
- [x] reimplement the palette refresh that became broken
- [x] default page (no hash) has been broken by new renderer init process, to be fixed, as well as iframe embedding probably
- [x] estimate the number of processors if possible :fast_forward:
  Only Chrome supports navigator.hardwareConcurrency, let's assume 4 cores for other browsers...
- [x] rework the build process because workers require their own external JS file :fast_forward: no need, the WW is embedded thx to a nice little trick; could be bothering for debugging, though...
- [x] code cleanup
- [x] test under four browsers :fast_forward: it worked nearly on the first try... I'm old enough to have sweated on IE6, so color me surprised

**Comment by methusalah** [comment]
test

- [x] reimplement the palette refresh that became broken
- [x] estimate the number of processors if possible
- [x] rework the build process because workers require their own external JS file
- [x] code cleanup
- [x] test under four browsers

**Comment by solendil** [comment]
Webworkers are here !

**Comment by solendil** [comment]
Tests with asm.js show no improvements in Firefox and a decrease of performance with Chrome. I implemented the core fractal function, then the tile drawing (in case the call overhead was causing the performance decrease) without success.

**Comment by solendil** [comment]
WebGL : limited to float precision on a lot of GC, which is not enough. Moreover, it seems the GC are not well suited to arbitrary precision math... I will get back to this when working on arbitrary precision
ES6 : concerns mostly JS syntax and is of no relevance to users. browser support will take some time to catch up, so no priority there
WebAssembly : far from being ready, but I'll jump in ASAP

Closing the ticket...
